// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models
{
    public partial class Furniture
    {
        public int? Price { get; set; }
        public string Type { get; set; }
    }
}