// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models
{
    public partial class Staff
    {
        public int? Old { get; set; }
        public string Name { get; set; }
    }
}